//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Booking_Date
    {
        public Nullable<int> bookingID { get; set; }
        public string location_room_id { get; set; }
        public System.DateTime date { get; set; }
        public int slotID { get; set; }
    
        public virtual tblBooking tblBooking { get; set; }
        public virtual tblSlot tblSlot { get; set; }
    }
}
