//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBookingDate
    {
        public int SNo { get; set; }
        public Nullable<int> BookingID { get; set; }
        public int LocationID { get; set; }
        public int RoomID { get; set; }
        public System.DateTime Date { get; set; }
        public int SlotID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusUpdated { get; set; }
    
        public virtual TblBooking TblBooking { get; set; }
        public virtual TblLocation TblLocation { get; set; }
        public virtual TblRoom TblRoom { get; set; }
        public virtual TblSlot TblSlot { get; set; }
    }
}
