//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBooking()
        {
            this.TblBookingDates = new HashSet<TblBookingDate>();
        }
    
        public int BookingID { get; set; }
        public int CreatedBy { get; set; }
        public int LocationID { get; set; }
        public int RoomID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int SlotID { get; set; }
        public int SlotCount { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
    
        public virtual TblLocation TblLocation { get; set; }
        public virtual TblRoom TblRoom { get; set; }
        public virtual TblSlot TblSlot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBookingDate> TblBookingDates { get; set; }
    }
}
