//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBooking()
        {
            this.tbl_Booking_Date = new HashSet<tbl_Booking_Date>();
        }
    
        public int bookingID { get; set; }
        public int createdBy { get; set; }
        public int location_id { get; set; }
        public int room_id { get; set; }
        public System.DateTime timestamp { get; set; }
        public System.DateTime fromDate { get; set; }
        public System.DateTime toDate { get; set; }
        public string subject { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Booking_Date> tbl_Booking_Date { get; set; }
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblRoom tblRoom { get; set; }
    }
}
