--------------------------------------------------------------------------------------------	Location Table																							
--create table tblLocation(
--locationID int,
--locationName varchar(30) NOT NULL,
--CONSTRAINT locationID_pk PRIMARY KEY(locationID)
--);

--------------------------------------------------------------------------------------------	Room Table
--create table tblRoom(
--roomID int,
--roomName varchar(30) NOT NULL,
--location_ int  NOT NULL,
--CONSTRAINT roomID_pk PRIMARY KEY(roomID),
--CONSTRAINT locationID_fk FOREIGN KEY (location_id) REFERENCES tblLocation(locationID)
--);

--------------------------------------------------------------------------------------------	Slot Table
--CREATE TABLE tblSlot(
--slotID int,
--slot varchar(30) NOT NULL,
--CONSTRAINT slotID_pk PRIMARY KEY(slotID)
--);


--------------------------------------------------------------------------------------------	Booking Table

--CREATE TABLE tblBooking(
--bookingID INT IDENTITY(1,1),
--createdBy INT NOT NULL,
--location_id INT NOT NULL,
--room_id INT NOT NULL,
--timestamp SMALLDATETIME NOT NULL,
--fromDate DATE NOT NULL,
--toDate DATE NOT NULL,
--slot_id int NOT NULL,
--slot_count int NOT NULL,
--subject VARCHAR(60) NOT NULL,
--description VARCHAR(250) NOT NULL,
--type varchar(20) NOT NULL,
--CONSTRAINT bookingID_pk PRIMARY KEY(bookingID),
--CONSTRAINT location_id_fk FOREIGN KEY (location_id) REFERENCES tblLocation(locationID),
--CONSTRAINT room_id_fk FOREIGN KEY (room_id) REFERENCES tblRoom(roomID),
--CONSTRAINT slot_id_fk FOREIGN KEY (slot_id) REFERENCES tblSlot(slotID)
--);

--------------------------------------------------------------------------------------------	Date-Booking Table
--CREATE TABLE tbl_Booking_Date(
--S_No INT IDENTITY(1,1) NOT NULL,
--bookingID INT,
--locationID INT NOT NULL,
--roomID INT NOT NULL,
--date date NOT NULL,
--slotID int NOT NULL,
--status VARCHAR(30) NULL,
--CONSTRAINT S_No_pk PRIMARY KEY(S_No),
--CONSTRAINT FK_tbl_Booking_Date_bookingID FOREIGN KEY (bookingID) REFERENCES tblBooking(bookingID),
--CONSTRAINT FK_tbl_Booking_Date_location_id FOREIGN KEY (location_id) REFERENCES tblLocation(locationID),
--CONSTRAINT FK_tbl_Booking_Date_room_id FOREIGN KEY (room_id) REFERENCES tblRoom(roomID),
--CONSTRAINT FK_tbl_Booking_Date_slot_id FOREIGN KEY (slot_id) REFERENCES tblSlot(slotID)
--);

--------------------------------------------------------------------------------------------	Booking table and Date-Booking table store procedure

--CREATE procedure sp_booking
--@createdBy INT,
--@location_id INT,
--@room_id INT,
--@subject VARCHAR(60),
--@description VARCHAR(250),
--@fromDate DATE,
--@toDate DATE,
--@slot INT,
--@slot_count INT
--AS
--BEGIN
--	BEGIN TRAN
--		IF(@slot_count>4 OR @slot_count<1)
--			RAISERROR(N'Invalid no of slots',16,1,@slot_count);
--		ELSE 
--		BEGIN
--			INSERT INTO tblBooking(createdBy,location_id,room_id,timestamp,fromDate,toDate,subject,description)
--			VALUES(@createdBy,@location_id,@room_id,current_timestamp,@fromDate,@toDate,@subject,@description);

--			DECLARE @bookingID INT;
--			SET @bookingID=(SELECT max(bookingID) FROM tblBooking);
--			DECLARE @FD DATE = @fromDate;
--			DECLARE @TD DATE = @toDate;
--			DECLARE  @count INT= 0;
--			BEGIN TRY
--				WHILE(@count<@slot_count)		
--				BEGIN
--					WHILE(@FD <= @TD)
--					BEGIN				
--							INSERT INTO  tbl_Booking_Date (bookingID,location_room_id,date,slotID)VALUES(@bookingID,Convert(varchar,@location_id)+'-'+Convert(varchar,@room_id),@FD,@slot);
--							SET @FD = DATEADD(DAY,1,@FD);					
--					END
--					SET @FD=@fromDate;
--					SET @slot=@slot+1;
--					SET @count=@count+1;
--				END	
--				IF(@@ERROR <>0)
--				BEGIN
--					ROLLBACK TRAN;
--				END
--				COMMIT TRAN;
--			END TRY
--			BEGIN CATCH
--					print ERROR_MESSAGE()
--					print  ERROR_SEVERITY()
--					print ERROR_STATE()
--					ROLLBACK TRAN;
--			END CATCH
--		END	
--END


------------------------------------------------------------------------------------------- Update store procdure	
--CREATE procedure sp_update_booking
--@bookingID INT,
--@createdBy INT,
--@location_id INT,
--@room_id INT,
--@subject VARCHAR(60),
--@description VARCHAR(250),
--@fromDate DATE,
--@toDate DATE,
--@slot INT,
--@slot_count INT
--AS
--BEGIN
--	BEGIN TRAN
--		IF(@slot_count>4 AND @slot_count<1)
--			RAISERROR(N'Invalid no of slots',16,1,@slot_count);
--		ELSE 
--		BEGIN
--			--INSERT INTO tblBooking(createdBy,location_id,room_id,timestamp,subject,description)
--			--VALUES(@createdBy,@location_id,@room_id,current_timestamp,@subject,@description);

--			UPDATE tblBooking 			
--			SET location_id=@location_id,
--				room_id=@room_id,
--				timestamp=current_timestamp,
--				subject=@subject,
--				description=@description,
--				fromDate=@fromDate,
--				toDate=@toDate
--			WHERE bookingID=@bookingId AND createdBy=@createdBy;

--			--DECLARE @bookingID INT;
--			--SET @bookingID=(SELECT max(bookingID) FROM tblBooking);
--			DECLARE @FD DATE = @fromDate;
--			DECLARE @TD DATE = @toDate;
--			DECLARE  @count INT= 0;
			
--			DELETE 
--			FROM tbl_Booking_Date 
--			WHERE bookingID=@bookingID;

			 
--			BEGIN TRY
--				WHILE(@count<@slot_count)		
--				BEGIN
--					WHILE(@FD <= @TD)
--					BEGIN				
--							INSERT INTO  tbl_Booking_Date (bookingID,location_room_id,date,slotID)VALUES(@bookingID,Convert(varchar,@location_id)+'-'+Convert(varchar,@room_id),@FD,@slot);
--							SET @FD = DATEADD(DAY,1,@FD);					
--					END
--					SET @FD=@fromDate;
--					SET @slot=@slot+1;
--					SET @count=@count+1;
--				END
--				IF(@@ERROR <>0)
--				BEGIN
--					ROLLBACK TRAN;
--				END
--				COMMIT TRAN;
--			END TRY
--			BEGIN CATCH
--					print ERROR_MESSAGE()
--					print  ERROR_SEVERITY()
--					print ERROR_STATE()
--					ROLLBACK TRAN;
--			END CATCH
--		END	
--END


--------------------------------------------------------------------------------------------	EXAMPLES

--------------------------------------------------------------------------------------------	Store procedure execution
--exec sp_booking 
--@createdBy=1,
--@location_id=2,
--@room_id=1,
--@subject='sub',
--@description='desc',
--@fromDate='1-1-2017',
--@toDate='1-3-2017',
--@slot=1,
--@slot_count=1;
-----------------------------------------------------------------------------------------------------------------------------------------
--exec sp_update_booking
--@bookingID=13,
--@createdBy=1,
--@location_id=1,
--@room_id=1,
--@subject='123',
--@description='lkasfdj;laskdjf;laskdjf',
--@fromDate='9-13-2017',
--@toDate='9-15-2017',
--@slot=2,
--@slot_count=1;